name: Daily Note Generator
on:
  schedule:
    - cron: "0 12 * * 1-5"  # Segunda a Sexta, 9:00 AM BRT
  workflow_dispatch:  # Permite execução manual

jobs:
  generate-note:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Necessário para commits posteriores

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Script
        run: python main.py
        env:
          VAULT_PATH: ${{ secrets.VAULT_PATH }}  # Caminho relativo ao vault no repositório
          OBSIDIAN_VAULT_NAME: ${{ secrets.OBSIDIAN_VAULT_NAME }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}  # Se usado
